CREATE USER postgres;
CREATE DATABASE football;
GRANT ALL PRIVILEGES ON DATABASE football TO postgres;

CREATE TABLE IF NOT EXISTS leagues (
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  type VARCHAR(255) NOT NULL,
  start DATE NOT NULL,
  end DATE NOT NULL,
);