version: "2.20"
name: football
services:
  db:
    image: postgres:15.5-bullseye
    restart: unless-stopped
    env_file:
      - ../backend/.env
    ports:
      - "5432:5432" # delete after deployment
    volumes:
      - ../backend/init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build: 
      context: ../frontend/
      dockerfile: ../docker/frontend_dockerfile
    ports:
      - "9101:9101"

  # user:
  #   build:
  #     context: ../frontend/
  #     dockerfile: user_dockerfile
  #   volumes:
  #     - type: bind
  #       source: ../backend/data/
  #       target: /data/
  #   stdin_open: true
  #   tty: true